### ISSUE TITLE
[Feature Request] Bulk of features.

### ISSUE THREAD

**Issue by PabloLION** [almarklein/timetagger#102]
Hi, almarklein and team. I like your idea on making an open source version of time tracker and how you executed it:  website with neat-font and european-japanese cute minimalist style, CLI tool, etc...  
I have a bunch of ideas in this field and the essential one is to add a new timeline of "plan" so we can know how much we are in control of ourselves. And with this new timeline we can merge much more functionalities than merely time tracking, like plan next week with todo; add tasks from todo list, classify todo list, form a new habit by tracking it, etc.  
Can I work with you guys? or it is against your original idea hence I need to fork this.

**Comment by almarklein** [comment]
Hi Pablion, thanks for your message. Glad you like TimeTagger :)

Its great to hear that you have ideas on how to add more functionality! However, TimeTagger is based on the idea to keep things simple. I am adding features over time, but everything still resolves around the idea of a simple, timeline-based time-tracker. Adding the functions that you mentioned may be useful (for some), but they would make this a different product.

I definitely don't want to hold back your creativity, and you are free to fork this project and change it to include your ideas. I would be honoured if this happened!

As for the licensing terms: this code is GPL3, which means that you can fork, make changes, publish your version, and you and anyone else can make use of your version. The license does prohibit you (or anyone else) from commercializing your derivative work. But if it ever gets this far, I'm sure that we can work something out :)

**Comment by Pablion** [comment]
@almarklein thanks for the response. I sent you an email on @almarklein.org .
Also while I run it locally using it, I've seen some misbehaviours and missing important features:
- Event(or track entry) will not update after input. I think it's now triggered by blur or focus event. Better to use "onChange" here.
- Need a button to zoom in/out since we have plenty of space, we can maybe add these buttons?
- We can click timeline to add event.
- Adding "already done" event can automatically start from when last event ends. 

As you are still maintaining this repo. I don't really want to create a new fork. I think the major credit should go to the original creator. As for GPL Licence, I would be content if I can build a welcomed tool even without economic income. I just want to make things work.

**Comment by almarklein** [comment]
> Event(or track entry) will not update after input. I think it's now triggered by blur or focus event. Better to use change event here.

Do you mean the description in the edit-record dialog? It is supposed to update on each change, and it does when I try. What browser are you seeing this on?

> Add a button to zoom in/out since we have plenty of space, we can maybe add these buttons?

This is not only a matter of space, but also of design and avoiding clutter. We've had zoom buttons earlier, but I replaced them with the multi-use range selection button: 
![image](https://user-images.githubusercontent.com/3015475/142990687-f8c1efc2-e4c1-4493-bbac-6e1411662a9e.png)

If you feel strongly about this, please create a separate issue, and we can see if other users confirm that they miss a feature like this. Now that I think of it, we could also make this an option to turn on in the settings.

> Click timeline to add event.

We also had this is the past: if you clicked the timeline, it would go into a mode where you could drag the new record. This apparently was rather confusing for users. I'm definitely not opposed to bringing it back somehow, but I'm not sure how. If you have ideas on how to make this work well in combination with *navigating* the timeline, I would love to hear. A separate issue would be good here too.

> Adding "already done" event always start from when last event ends ( now only for <3h or so ).

Well, I don't think you'd want it to snap to a time more than 24h ago, so having *some* limit makes sense, I think. But 3h is indeed rather short. What about 8h or 12h? Should be a relatively easy contribution ;)  

> Edit tag keeps tag color

Sorry, I don't understand what you mean here.

> Comment section with multi-line for event details (to search only in description)

It is a deliberate choice to keep the description a one-liner.

**Comment by Pablion** [comment]
Sorry last night I was kind of sleepy, I now see some ambiguity here. Trying to make it clear now.

> Event(or track entry) will not update after input. I think it's now triggered by blur or focus event. Better to use change event here.

I know the "description" does update on "change", but the "starting time" and "ending time" doesn't. Sorry I didn't call it out. Also I think we should implement some time parser here like "1300 -> 1:00 pm" or "1300 -> 13:00" (for 12h/24h distinctively).

> Add a button to zoom in/out since we have plenty of space, we can maybe add these buttons?

I'm now agreeing more on this(keep the panel clean) after thinking about responsive design. Maybe we can change the up/down arrow to the zoom since we can directly move timeline with the scroll wheel.

> Click timeline to add event.

I used toggl desktop, on windows it was correct and on Mac it's much worse. I totally understand the conflict of between dragging to adjust and clicking/dragging to add. I meant to ask you if you think it's good. If so, the rest is all UI/UX technique, like click somewhere/ some button to enter/switch timeline create/update mode, etc. In this case, I think an extra issue for this thread is needed.

> Adding "already done" event always start from when last event ends ( now only for <3h or so ).

I think it's like 4h after logging with time-tagger today. We can add an user option to decide the hours and let users to decide? This feels more free. I'll start contributing with this easy PR.

> Edit tag keeps tag color

This is when I batch rename tag, the color of the tag didn't maintain.

> Comment section with multi-line for event details (to search only in description)

I want to keep everything in one place for my later search... I used obsidian.md (top tier noting app for me) but it's just not designed for time tracking.

**Comment by almarklein** [comment]
> Do some server settings so the self-hosting user can visit from mobile devices(cellphone/tablet). I don't know how to do it right now.

I don't think we need anything here. The user must host it somewhere where it can be reached by the mobile device. Can be in the cloud, but also on a local network. It's up to the user to implement authentication/authorization though.

> Enable "search"

That sounds reasonable. Perhaps as part of the tag edit dialog (it currently supports search, but only for tags).

> Enable "undo"

Implementing undo properly can be very challenging. Since most actions can be undone quite easily, I don't think this is worth the effort (and extra complexity).

> Enable timeline zoom in/out with magic trackpad.

+1

**Comment by Pablion** [comment]
about 9. Enable "undo"
> Implementing undo properly can be very challenging. Since most actions can be undone quite easily, I don't think this is worth the effort (and extra complexity).

I totally understand you after you calling it out. This request does have a low priority for me. (continue my writing) In the recent hours I've been busy so I think my mindset has changed, I now value more the ease of time tracking and this is mostly affected by the UI, instead of the data structure, or interaction model. I'll try to make some PR soon.

**Comment by almarklein** [comment]
>  I think it's better that you invite me to the repo 

Access to a repo is reserved for owners and maintainers of a project. PR's and issues are a perfectly suitable way to contribute code and ideas.

**Comment by Pablion** [comment]
Hi almar, 
After some thinking, I decided to start a new project with TypeScript (typing is python is uncomfortable for me) since you don't want to add a "plan" timeline, which is my priority feature request. You may close this issue or leave it open to gather some useful pieces of advice for you.
Regards.

**Comment by almarklein** [comment]
Cool! Keep us posted on the progress!

I'm leaving this open for the moment, since some "lighter" features that were mentioned are certainly interesting.

**Comment by almarklein** [comment]
To be clear, I don't think that the bigger ideas you proposed are a bad idea - they can be great if done well. But they don't fit into what TimeTagger is, and it's not a direction I want TimeTagger to grow into.

Distillation of features that make sense IMO:

* Info does not update when changing date/time input. 
* Add a button to zoom in/out, maybe enabling this with a setting?
* Increase the time to snap "already done" to the last record (3h -> 8h or so).
* Editing the tag in the manage-tags dialog does not update the color.
* Option to search for text in the manage-tags dialog.

**Comment by almarklein** [comment]
The list mentioned above has now been imlpemented (and is also live).

**Comment by dzmitry-lahoda** [comment]
I see `todo` was mentioned:

- so i can create tagged task, but not start (on right of my screen)
- so I can have pool of tasks
- i choose tags and find I want and drag(start) task to the left
- it starts, removed from todo, and became time

i will donate 1 DOT for such feature (or integration with tagged todo app if such exists)

**Comment by PabloLION** [comment]
@dzmitry-lahoda I wanted to build some thing larger than only todo. And @almarklein think it would be too complicated.
What do you mean by 1 DOT?

**Comment by dzmitry-lahoda** [comment]
1 DOT is polkadot crypto)

there was idea for some tag cloud. for me todo is big cloud of tags, so i can drill into narrowin tags. than just move it into timeline to start.
