### ISSUE TITLE
🐞 Data loss with a large tag presets

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#126]
Hi
maybe it's not the amount but certain characters that cause the problem?

The problem:
If I enter the list of tags below as preset → I get a save confirmation BUT the list is not available afterwards - so it seems it is not saved.

#kleinkram 
#kommunikation 
#fokus 
#unterbrechung 
#overhead-unternehmensplanung 
#overhead-personalmanagement 
#overhead-prozesse 
#overhead-prozessabwicklung 
#govb-dev 
#govb-test 
#ai 
#gu 
#wkis 
#wkobase 
#forbildung-aktiv 
#fortbildung-passiv 
#abwesend

**Comment by Floehe** [comment]
I can also confirm this problem... at some point it stops saving additional tags in the presets

**Comment by almarklein** [comment]
I think I see what the problem is. The preset info is stored in the "settings store". Which is basically a key-value store, and the values are allowed to be no longer than 256 chars. That limit was introduced to prevent misuse, and 256 is more than enough for most settings ... but is obviously a bit restrictive for this particular setting.

I think I'll:
* Increase the max-size of setting values.
* Check the size in the dialog to prevent surprises.

**Comment by almarklein** [comment]
Fixed, released, and deployed. 🚀
