### ISSUE TITLE
Home/End unexpectedly change the time scale when it's smaller than 1-day

### ISSUE THREAD

**Issue by ouuan** [almarklein/timetagger#149]
When the time scale is smaller than 1-day (i.e. only a part of a day is shown on screen), Home/End changes the time scale to 1-day. According to its description, it should keep the current time scale, which is the behavior I want.

After the "snap to now", I suggest the "now" appear at around 60% to the top. I also want this position of "now" when the time scale is exactly 1-day.

What's more, I think it's better to call the functionality of <kbd>Home</kbd>/<kbd>End</kbd> "snap to now" without "(on current time-scale)", and simply call the functionality of <kbd>D</kbd> "select today", not "snap to now".

**Comment by ouuan** [comment]
It seems that simply removing this does the job:

https://github.com/almarklein/timetagger/blob/4c8d044ecb8918682ceb04abd6a2c3b381f74636/timetagger/app/front.py#L1269-L1270

So this turns out to be the intended behavior. Feel free to reject my request. I can make this change in my fork.

**Comment by almarklein** [comment]
The behavior of the "today"button has changed in the past, so it could be that some of the behavior is still a bit off for historic reasons. Though I think that snapping to a full day when zoomed in to a range smaller than a day, was intentional because I expected this to be a better behavior, but I see how it can also be annoying. I will have a look at this.

**Comment by almarklein** [comment]
Nice digging, by the way - these were indeed the lines that should be removed. Done in #156.

**Comment by almarklein** [comment]
Fixed and deployed 🚀
