### ISSUE TITLE
Access presets and recents via the keyboard, take 2

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#174]
Good point made here: https://github.com/almarklein/timetagger/pull/169#issuecomment-1044060355

 I think we can distinguish (at least) 3 use-cases:

1. The user is looking for a preset. Worked good previously, and still does.
2. The user is looking for a recent tag only. Did not work so well, this PR fixed that.
3. The user is not sure what to look for. I had not thought of this and broke this use-case :)

Some ideas that come to mind:
* When typing "#", show presets first, then recents. When you start typing, the matches show recents first and then presets. No more "##".
* Keep distinction between "#" and "##", but it only determines the order: With "#" show recents and then presets. With "##" show presets and then recents.

**Comment by GitHofi** [comment]
Hi @almarklein 

Thanks for bringing this up again. 

After 1 day of working with the new feature ##, I could see that it is not quite as bad as I had feared. This is due to 2 things...

1. I actually only use pre-defined tags and don't create any on-the-fly. That means I might as well put all the single tags I use into the presets. This is a bit of work at first - but then it works well.
2. also ##new-tag is automatically saved as #new-tag. This makes it possible to create tags quickly, even if they were not yet available as preset. (I.e. I don't have to rework the entry completely).

Thus it is actually "quite ok". The only thing that is unnecessary but bearable is the double ## that I always have to enter now. But I could live with that.

About the idea:
> When typing "#", show presets first, then recents. When you start typing, the matches show recents first and then presets. No more "##".

This would be exactly counterproductive for me, because I search the matching presets by typing the first letters.

For example, I have the following presets:
- #bits-and-pieces #staff
- #bits-and-pieces #planning
- #bits-and-pieces #team-A
- #communication #staff
- #communication #team-A
- #communication #team-B
- #communication
- #team-A
- #team-B
- #focus
- ... and so on

What I do is type: #team -> and wait, what the autocomplete comes up with and select the one that matches best.
In my example I would get 5 matches:

- #bits-and-pieces #team-A
- #communication #team-A
- #communication #team-B
- #team-A
- #team-B

If I have an exact match for the desired combination of tags - great. Otherwise I choose the preset #team-A or #team-B (what I just needed) and create the desired combination myself by typing the missing part (like #focus).

I currently see 2 possibilities...
(A) leave it as it is
(B) an option in the settings, whether presets or recent should be shown first.

**Comment by almarklein** [comment]
What is your thought about the other option I mentioned: always show both recents and presets, but with "#" recents go first, and with "##" the presets go first.

**Comment by GitHofi** [comment]
Hello,

yes, the second suggestion would restore the previous state, with the difference that I then (as now) always have to use double-hashtag. So yes, it would be an improvement for me - but with the downside that I always have to type ##.

⇒ I can live with that.

If it's not too much trouble, I would additionally appreciate an option in the settings where I could choose whether # or ## displays the presets first. (But as stated above - I can also live without such an option)

Thanks again for your efforts to make the feature as universally usable as possible 👍

**Comment by GitHofi** [comment]
Perhaps one additional comment:
Before spending to much time on the above mentioned settings option, it would be much more helpful (for me personally) if you invested the time e.g. in "💡 exclude individual tags from the report #128".

**Comment by GitHofi** [comment]
After working with version 22.2.3 for another 2 days, here is my summary:
**For me, it can stay as it is.** I de facto only use the presets and can live with the double hashtag ( and have tinkered with a workaround 😉 ).

The key feature for me already exists ("##new-tag" not only triggers the presets, but can also be easily saved as a compete new tag) - so I don't have to think to much in front 👍 

We have discussed possible improvements above anyway, for me only the addition via the settings would bring a little relief. But I'm not sure if it's worth the effort.

Thanks for keeping an open ear for further improvements.
Chris

**Comment by almarklein** [comment]
The solution that I implemented was to enable toggling between presets/recens by typing '#' while the autocompletion is active. This also works if you've already typed some characters.

I don't think this improves your workflow much, @GitHofi, but it's generally more flexible that the previous solution.

> it would be much more helpful (for me personally) if you invested the time e.g. in "💡 exclude individual tags from the report https://github.com/almarklein/timetagger/issues/128".

This is next on my list 👍
