### ISSUE TITLE
Small "bug" when window is narrow (description field doesn't get focus)

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#192]
If the window (desktop; chrome) is made so narrow, that the layout changes to a separate view (only records or only overview), then you can use the shortcut "s" to open the dialogue window for entering a new record, BUT the description field does not get the focus. This means that you cannot start typing straight away, but must first click on it with the mouse.

I hope this can be easily fixed.

Thanks
Chris

**Comment by almarklein** [comment]
This is because of this:
https://github.com/almarklein/timetagger/blob/0baf2c4c2641880bf1158f8d70d50484353026e7/timetagger/app/dialogs.py#L1121-L1124

The `looks_like_desktop` function just looks at the size of the window, so when you make it very narrow, it things you're on a mobile device. I could try to find a more reliable way to detect mobile devices. Your particular case might even be solved by also checking the height ...

**Comment by GitHofi** [comment]
Thanks for having a quick look at it.

The reason I discovered this is, that I like the "mobile layout" and thought I could use it this way on my desktop. It's cleaner with less distraction. I don't need the overview while recording through the day. After a working day I switch to "overview" and get the Info I need.

**Comment by almarklein** [comment]
Thanks for explaining your use-case. I agree that it should be possible to use a smaller window on desktop too.
