### ISSUE TITLE
Merging Resumed Tasks in Report

### ISSUE THREAD

**Issue by jasonrhancock** [almarklein/timetagger#228]
For resumed tasks separated by other tasks throughout the day, it would be nice to have the option during report generation to have those combined into one entry per day.
In this case, I only care how much total time I spent on each task per day.

**Comment by almarklein** [comment]
The report shows individual records, and totals for groups. The point of the individual records is that these show the detailed times. The point of the groups is to show combined statistics.

I therefore suspect that by tweaking the options in the report dialog (especially the grouping option) you can get what you're looking for. I'd suggest setting the grouping to "date / tags" or "tags / date", not hiding secondary tags, and then disabling the "show records". If needed you could add a tag to the records that you want to group in particular. You can make these tags secondary (in the tag manage dialog) so that they don't influence the sorting process.

**Comment by martin-braun** [comment]
@almarklein I don't get it, I have the same problem.

I resumed a task several times, but it has the same tags like some other tasks. How can I now combine those tasks to see how long I've worked on this particular task. Example:

<img width="689" alt="Screenshot 2023-07-03 at 08 37 41" src="https://github.com/almarklein/timetagger/assets/24259245/4b5c10ca-c05e-41dd-adb5-3c7ab021862c">

Could you please tell me how to get the total hours of this particular task?

**Comment by almarklein** [comment]
If you set the grouping to "tags", you should get an overview like this, with the totals per tag-combination:

<img width="798" alt="image" src="https://github.com/almarklein/timetagger/assets/3015475/7aa8928b-2056-4a23-93e9-67efc3bc6ffa">

You can also group by "tags / dates" or "date / tags" to get totals per day. If you disable "show records" it'll only show the totals (not the individual records).

----

By the way, in the overview panel, you can click on a tag to select it, and then on another to select the combination and see the overview specific to that combination:

<img width="606" alt="image" src="https://github.com/almarklein/timetagger/assets/3015475/2822c406-659d-4d2a-896d-4c8ab6406c14">

**Comment by martin-braun** [comment]
@almarklein Unfortunately, this doesn't solve my issue. 

In your example, how can you group all "Did some stuff #client1 #meeting" together? ... Because this is what I need. My client asks for the exact hours on every task, but a resumed task with the very same name, should count as one task.

I'm stuck counting times at this point, because those tasks share the same tags.

**Comment by almarklein** [comment]
Thanks for the explanation @martin-braun. I now also see that this is really a duplicate for #348. Will continue the discussion there, as that issue is still open.
