### ISSUE TITLE
Check mark or 'x' with a spiral moving around it - what is it?

### ISSUE THREAD

**Issue by lgaudreau** [almarklein/timetagger#230]
What is the  check mark or x in the upper left corner beside the menu with a spiral going around it?  It's not mentioned in the docs anywhere from what I can tell, and there is no tooltip when hovering over it.

What does it mean when it's an 'x' and what does it mean when it's a check mark?

**Comment by almarklein** [comment]
That's the sync-indicator. It shows when it syncs with the server (push changes and receive updates). A `+` means that it has pending changes that need to be pushed. A checkmarks means that the sync was sucessful, a cross means that either the server or your internet connection is down.

I'll leave this issue open. This should indeed be documented somehow!

**Comment by lgaudreau** [comment]
Thanks, I figured it was something like that but am getting the 'x' more than I expect I should, I'll have to look into that (using the self-hosted version); glad to see it will be added in to the documentation.  I've been enjoying the program so far!

**Comment by almarklein** [comment]
I'm not 100% sure, but IIRC an error message is written to the console (F12 in the browser) on a fail. That may provide more info (e.g. request timed out, or internal server error).

**Comment by lgaudreau** [comment]
Great, thanks - I'll check that the next time I notice it happening.

**Comment by lgaudreau** [comment]
The console suggestion was great, thanks - it turns out Authelia was timing out causing the disconnection.  

I did see another suggested post on improving the documentation for customizing user logins; if I could have Authelia handle all user logins and pass the authentication to Timetagger that would be great.  At the moment I authenticate with Authelia, then log in to Timetagger still.

**Comment by almarklein** [comment]
I'm not sure how you've set things up. Have you've modified the TimeTagger server to authenticate each request via Authelia?

The approach that I intended (this does not mean that you must do it this way :) ), is that you use *some* auth solution to get a first (timetagger-specific) webtoken. From there on, only the webtoken is used, and the other auth service (e.g. Authelia) would only be needed when you log out again (either explicitly, or because the webtoken expires).

Relevant docs:
* The post about using custom auth: https://timetagger.app/articles/selfhost/
* The new post on a simple builtin auth mechanic: https://timetagger.app/articles/selfhost2/

**Comment by lgaudreau** [comment]
Thanks for the links.  I set Timetagger up using a modified version of the older run.py file that is no longer on the Github site.  I see in the example configuration linked on the 'selfhost2' page it has an example for Authentik; I'll see if I can do something similar with Authelia or investigate migrating to Authentik for SSO.

**Comment by almarklein** [comment]
Might be good to make it more clear somehow that there are pending changes that are not yet sent to the server. This might avoid #232

**Comment by almarklein** [comment]
I think it should be more clear, with the recent tweaks.
