### ISSUE TITLE
Recording doesn't always stop

### ISSUE THREAD

**Issue by eldelacajita** [almarklein/timetagger#232]
Lately I've been having this issue where I click "stop" and the recording _does_ seem to stop, but when I come back to work I find the recording had actually not stopped and is still counting.

I don't know exactly how to reproduce it, but it happens quite frequently. I'm using TimeTagger on mobile as a pinned Firefox web app, and on my PC as a GNOME Web (Epiphany) web app, but the error doens't seem to depend on having both open at the same time.

Is this happening to anyone else?

**Comment by almarklein** [comment]
My first guess is that it might be related to the sync delay. When you make a change (e.g. stop a record) the sync indicator in the top left will show a plus (indicating pending changes). It will take 3 second or so before these changes are sent to the server. If you close the app before the sync takes place, the server wont receive it. On PC the sync still happens when you select another tab or application. I'm not sure whether this is also the case on mobile.

When the app is opened again later, the change should still show, and it should sync at that moment. But if you open the app on another device first, then that change will not be there (because it has not been sent to the server yet).

Could this explain the behavior that you're seeing?

**Comment by eldelacajita** [comment]
Thanks for the reply! 

I'm pretty sure this happens even if I give the app enough time to sync to the server. From now on I'm always going to check if the app has synced before closing or opening it on another location, and I will see if the issue appears again.

**Comment by almarklein** [comment]
Any news on this? If not, I'll close the issue. You can then always re-open if you confirm this as a bug in the future. I also added a note related to this issue in #233.

**Comment by eldelacajita** [comment]
It seems that more carefully waiting for the sync indicator to finish its cycle fixed these issues. Basically, avoiding to stop a running task and immediately close the app. So yes, you can close this :+1:

**Comment by almarklein** [comment]
My apologies, I somehow failed to see what's actually happening earlier:

1. you make a change, which is applied locally to the in-memory data structure.
2. When the sync indicator is done, it will
  a. apply the change to the persistent browser database (`indexedDB`)
  b. try to send the changes to the server

So if you close the browser before the sync action is performed, you indeed lose these changes.

Browsers have an API to tell it that there is "unsaved data", so that the browser can open a popup when the tab is closed. We could probably use that here.

**Comment by eldelacajita** [comment]
Oh, interesting!

 Is it possible to deliver a specific message with that popup? Maybe ask the user to just wait for some seconds for sync to finish, or something like that?

**Comment by almarklein** [comment]
> Is it possible to deliver a specific message with that popup?

Yes, you can specify a custom message (and the PR does that), but all modern browsers chose to ignore it 🤷

**Comment by almarklein** [comment]
I guess in theory we could make the unload callback trigger something in the app, so that it's visible in addition to the popup ...
