### ISSUE TITLE
Option to start a new record and auto-stop the current running record

### ISSUE THREAD

**Issue by gh4w** [almarklein/timetagger#27]
Hello. Thank you for your software.
Once thing i do frequently is switch from one task to another. Currently this means stopping the current record and then starting a new record.
Is there a way to just switch to a new record, stopping the current one, and running a new one ? 
If not, as a feature request, there could be a list of already existing tags in some dropdown where clicking on an entry would stop the current record and create a new one with the tag. 
What do you think ?

**Comment by almarklein** [comment]
I see your point. I rephrased the title to what I think is needed. This needs some thought and has some overlap with other comments (e.g. to combine the "start record" and "add new record" buttons in some way).

**Comment by thalelinh** [comment]
Coming from gtimelog, which allows me to log what I've been doing since the last record, I would appreciate this, as it kind of follows the same principle, specially if it allows me to edit the auto-stopped task description.

But actually, my use case could also be fulfilled if the "New record" form had the option to set the start time as the last record's end. :man_shrugging:

**Comment by almarklein** [comment]
@thalelinh interesting use-case! It's classic to forget putting on the timer and only realizing when you start a new task. A lot of  great ideas related to starting the timer coming in. Thanks all!

**Comment by almarklein** [comment]
The workflow for starting/creating/stopping/editing a record have been refactored. The new version is live now. Please let me know what you think!
