### ISSUE TITLE
Add search to main UI and/or to record dialog

### ISSUE THREAD

**Issue by eldelacajita** [almarklein/timetagger#274]
## Summary

This is a feature request to make search more accessible and practical when creating new records, helping us to:

* Avoid having to manually enter a description for recurrent or frequent tasks..
* Avoid creating multiple entries with different descriptions for the very same task.
* Avoid creating multiple entries with different tags for the very same task.

## Current situation and use case

- When creating a new record, very frequently I want to reuse an existing description, or take it as a basis and edit it slightly.
- Presets do help, but only for tags, not for the actual description. And I wouldn't want to have hundreds of presets.
- So search is the best option: you search for a term, click on the entry that is most similar to what you want so you can edit it, and then create a new record based on that one by hitting "Resume" and then editing the description if needed.
- BUT search is hidden away inside the hamburguer menu, and using it for this purpose is not very practical.

## Possible improvements

1. Make the search button permanently visible in the UI.

or 

2. Add search to the record creation/edition dialog itself: 
  **2.a.** Add a search button near the presets button. It would pop up the existing search window, and once you pick an entry in the search results, go back to the record creation/edition window with the selected description filled in.
  **2.b.** Just start typing in the description field and see a drop-down list similar to the one in the search dialog, showing related options in real time. Clicking on one of the results would put it into the description field to be further edited if needed.

or

Any other ideas?

**Comment by almarklein** [comment]
I must admit that I very often scroll to yesterday, find the record similar to what I'm about to do, and "resume" it. So I think you do have a point.

The challenge would be integrating it into the record dialog (because I think that's the place where such a feature would really shine). We already have two search modes (for tags, and presets). I'm not sure yet whether that's a downside (it would be confusing to add yet another mode), or an upside (3 modes is just one more than 2). So I think this will need some experimentation.

**Comment by almarklein** [comment]
Ok, I gave this a stab. The record dialog has an extra dropdown, and also shows recents when you start typing the first word (and it is not a tag). Let's see how this goes ...

**Comment by almarklein** [comment]
> How many entries are considered "recent"? I

https://github.com/almarklein/timetagger/blob/7c9cf3f897bf41ee13a5bdb595686c5c21948aab/timetagger/app/dialogs.py#L1369-L1374

**Comment by almarklein** [comment]
It's released and deployed 🚀

**Comment by eldelacajita** [comment]
12 weeks seems reasonable. For now I don't think I'd need to configure it to a different value.

Also, thanks for the ultra fast release! I'm testing it and I'm loving it so far :clap:  :sunglasses:

**Comment by eldelacajita** [comment]
Just came back here to say that this feature has proven to be SOOO useful :star_struck: Thanks!

**Comment by Tagirijus** [comment]
I like the idea of this feature and the implementation. Yet what if there is a really old task I want to resume after years? In such a case I cannot find it in the recent list, since it's more than 12 months old. Would it be to performance heavy without such a limitation of the range and just get all used tags ever, yet with the sorting of the last usage or so? You wrote it could be configurable in the future, after all, hehe. Still wondering if a range of maybe 10 years would kill the app then! :D

**Comment by almarklein** [comment]
Only showing moderately recent tags is a deliberate choice because it would mostly be annoying to see tags of years before. Tags are light, so you probably should not care what tag you used 10 years ago 😉  but if you do, you can always use search to look it up. Then after using it once, its back in the list for another year.

**Comment by almarklein** [comment]
Then it's probably 12 weeks. I did not know the exact number.
