### ISSUE TITLE
Switch to today automatically (if resuming the task of yesterday)

### ISSUE THREAD

**Issue by guettli** [almarklein/timetagger#362]
In the morning I open timetagger.

I want to resume the last task I did yesterday.

I click on resume.

This works.

But I still see yesterday.

It would make sense if I automatically see the current day, if I resume the task of yesterday.

This would be more convenient.

**Comment by almarklein** [comment]
That makese sense! 👍

**Comment by almarklein** [comment]
Released! 🚀

**Comment by ouuan** [comment]
I think the problem is not specific to resuming. It's for all kinds of starting a new record when today is not focused.

**Comment by almarklein** [comment]
> I think the problem is not specific to resuming. It's for all kinds of starting a new record when today is not focused.

Which cases are you thinking off? The case for using resume is that it's likely that the user scrolled to an earlier task specifically to resume it, so it makes sense to snap back to today. But if the user starts a new task while today is not in view, the user may not want to snap back to today (and it may be perceived as annoying if the app did that). And otherwise, the today button is only one click away 😃
