### ISSUE TITLE
Remove character limit in Description field

### ISSUE THREAD

**Issue by WilderDrone** [almarklein/timetagger#370]
Hi

Till now I was using an excel sheet for logging my activities, I was looking for an app with some presets & tagging capabilities. This seems to cover a lot of what I was looking for.

Have a few feature requests which I was hoping would be possible -

1) Remove character limit in Description field - I sometimes make extensive notes for a particular activity, is there a way to remove the 255 character limit there currently?

2) Split Timer - I like to log the entire 24 hours, it would be nice to have a split timer like function where as soon as you press a button one activity ends and the next one begins automatically without having to necessarily specify a tag or description or anything all of which one can go back and fill in later

3) Fonts - it would be nice to be able to choose from different fonts

Some questions - 
1) Are there any app limits in the number of Presets or Tags etc, as in how big the app data becomes? 
2) Are you expecting to launch an android version so it can be used when one is offline?

Thanks

**Comment by almarklein** [comment]
Hi!

I'll respond to each question here. I created an new issue where it makes sense, and will close this one. But feel free to respond to my answers on this issue 👍 

> Remove character limit in Description field - I sometimes make extensive notes for a particular activity, is there a way to remove the 255 character limit there currently?

I made an issue to track this idea:  #375. The short answer is, no, this cannot be done yet, Maybe it can be added in the future.

> Split Timer - I like to log the entire 24 hours, it would be nice to have a split timer like function where as soon as you press a button one activity ends and the next one begins automatically without having to necessarily specify a tag or description or anything all of which one can go back and fill in later

I think this is already supported, though perhaps needing one extra click: just press the start button and the "start", to start a new record, stopping the currently running record. Or use shortcuts. Hit "S"  and then "Enter".

> Fonts - it would be nice to be able to choose from different fonts

The fonts are carefully selected to go with the design and e.g. use narrower fonts on smaller screens where it matters. Any particular reason why you'd want a different font?

> Are there any app limits in the number of Presets or Tags etc, as in how big the app data becomes?

There is a limit of 10MiB per update, but that's a lot of presets 😄. There is no limit for the tags, since these are implicitly defined in the description. The server does not even know about tags.

> Are you expecting to launch an android version so it can be used when one is offline?

No. But the app is a PWA, so you can "add it to the home screen"  from your mobile browser, and it will look and feel like a native app. TimeTagger is designed to work well off-line: all changes are stored on the device and are synced to the server when the connection is available again. (This also works when just using it from a browser tab BTW.)
