### ISSUE TITLE
[bug] Too many tasks make overview unreadable

### ISSUE THREAD

**Issue by Tagirijus** [almarklein/timetagger#407]
If you have too many tasks and filter nothing and maybe chose a time range which might cover all, the overview gets so crowded that you cannot read the last tags any more (the one with the least amount of time). Maybe you should add some kind of scrollbar to the overview panel on the right, when too many tag-combinations are shown there.

Also on mobile it happens really fast that the time for the tag-combination is unreadable if there are only some tags too much. Not sure how to solve this in a proper way, thought. Maybe decreasing the font size might help here already a bit.

**Comment by michaellenaghan** [comment]
My wife just started using TimeTagger. She ran into this problem rather quickly.

She has several clients. For each clients, she does many kinds of things. That produces a long list of client/task combinations in the overview — esp. when she zooms out to "month". 

The client/task combinations in the overview seem to be sorted by time; clients with more hours are higher in the list, and clients with fewer are at the bottom. Since the list was long and didn't scroll, she couldn't get to the clients at the bottom. (She wanted to filter by the client at the *very* bottom in order to generate a report.)

We came up with two workarounds.

One is to search for the client's tag, and then click on a *date* in the list of search results. That takes her to a day that's guaranteed to have entries for that client. She can then filter by the client and zoom out to "month" to generate a report.

The other is to search back in time, day by day or week by week, until that client shows up. In this particular case that turned out to be quite annoying, because that client had very, very few hours. (In other words, it took a while to find a day that included that client.)

Being able to scroll the right side would be one way to solve the problem.

Being able to directly type in tags to filter on would be another.

(Scrolling seems more generally useful; maybe you want to explore rather than filter?)

**Comment by almarklein** [comment]
Thanks for the detailed use-case where you hit this problem as well. The analysis of the two workarounds are also very helpful.

I agree that scrolling makes a lot of sense, because the fact of having a list that cannot be fully observed does not feel very elegant ...

To share some thoughts about the technical background on that: the main app is all drawn on the canvas, so there is no DOM/CSS that we can use to make something scrollable - it'd require the scrolling to be implemented from scratch. Probably still worth the effort though.

**Comment by michaellenaghan** [comment]
> it'd require the scrolling to be implemented from scratch

That sounds like a big ask! I wonder if there's a middle ground?

Some quick off-the-cuff thoughts:

* What if, somewhere, there was a tag cloud of all of the tags that show up in the list, and you could click on the tags to filter/unfilter by them? (The Report dialog is an obvious candidate.)

* What if there was a way to zoom in/out when the list was too long to fit? For example, what if repeated tags "collapsed" if the list was too long, and clicking on them "zoomed in"?

* What if there was a More... button that opened a dialog when the list was too long to fit? (I'm assuming that "in a dialog" is easier because Search results scroll.)

The third idea, the More... button that opens a dialog, seems like it might be the most palatable. 

First, the button would only appear when the list was too long; many users would never see it, and maybe many others would rarely see it.

Second, it replicates the functionality that the list currently gives you: you see not only the tag combinations used in the period, but also the time associated with the combinations — exactly what you get right now.

Third, if you ever got around to making the actual list scroll it would be easy to make the More button disappear without really affecting users.


(The first idea, the tag cloud, only addresses one specific use case: creating reports. Useful in its own right, but not really equivalent. The second idea, zooming, adds significant complexity. I left them in because maybe you can think of better variations?)

**Comment by almarklein** [comment]
Thanks for all the suggestions! I like how that more-button could be a relatively easy start towards a scrolling overview ... 🤔

**Comment by almarklein** [comment]
Scrolling is supported in the latest version!

**Comment by michaellenaghan** [comment]
Excellent, thank you!

**Comment by almarklein** [comment]
That's odd, it does work for me. Could you please double-check that its on the latest version (in the menu it should mention 23.11.2), and refresh if not?

I did find another problem: since the bars respond to pointer-down events, there is no way to swipe-scroll this list on mobile 😄.

I created #425 to track these issues.

**Comment by Tagirijus** [comment]
I did refresh before testing and yes, the menu says version 23.11.2. Oh and yes: swiping on the overview list does not work. I forgot to mention! :D

**Comment by almarklein** [comment]
Thanks for double-checking. I noted both problems.
