### ISSUE TITLE
Add documentation for nonroot Docker variant

### ISSUE THREAD

**Issue by kraftner** [almarklein/timetagger#409]
I just noticed the new option of having a non-root Docker container as introduced by #357.

Unfortunately I couldn't find any documentation on it, especially any required manual migration steps as mentioned in https://github.com/almarklein/timetagger/pull/357#issuecomment-1685026399.

I'd be willing to help with writing the documentation but it would probably be more efficient to get a head start by knowing what we're talking about here. Just `chown`-ing the data directory? Any pointers here @danielhass?

**Comment by danielhass** [comment]
Hi @kraftner, thanks for your interest in the new `non-root` variant. Sorry that there isn't already some documentation about this new variant available, somehow I haven't found time to sit down and properly document this.

Basically all there is to know can be found in the new [Dockerfile](https://github.com/almarklein/timetagger/blob/main/deploy/repo.nonroot.Dockerfile).

The new `non-root` Dockerfile expects a persistent data directory to be mounted at `/opt/timetagger` - see [here](https://github.com/almarklein/timetagger/blob/main/deploy/repo.nonroot.Dockerfile#L17)

Furthermore, if you are migrating from an existing installation, you have to make sure that the timetagger data which is the content of the data directory is owned by _uid 1000_ - see [here](https://github.com/almarklein/timetagger/blob/main/deploy/repo.nonroot.Dockerfile#L15)

That should do the trick. I can verify these steps on my side over the next few days if you want as it is quite a while ago since I did it myself. If you are willing to contribute docs feel free to do so, beside the final review form @almarklein I can also help with a first look. However as discussed in the [PR](https://github.com/almarklein/timetagger/pull/357#issuecomment-1685096763) we should probably add some general documentation regarding the containerized deployment and not only cover the `non-root` variant.

**Comment by kraftner** [comment]
Thanks @danielhass for your quick answer which did already lead me in the right direction.

First of all: I think I have successfully migrated to the non-root version.

What I am unsure is if putting the data directory *inside* `/opt/timetagger` as `/opt/timetagger/_timetagger` instead of next to it at `/opt/_timetagger` like in the root example would be less confusing for the sake of consistency when someone compares them. What do you think?

I'll open a PR on my changes up until here in a minute.

**Comment by danielhass** [comment]
@kraftner thanks for the PR; I'll but my thoughts in there and also comment on the data directory discussion there.
