### ISSUE TITLE
Add option for Monday-Friday week

### ISSUE THREAD

**Issue by Elarnon** [almarklein/timetagger#417]
Or: TimeTagger wants me to work every weekend.

When setting tag targets, it seems like TimeTagger always defaults to a 7 day work week. If I set daily targets, when the "week" view, I am at only around 71% even if I reached all my daily targets for the week, because TimeTagger insists on counting Saturday and Sunday. If I set weekly targets, the % in the week view is correct, but in the daily view, TimeTagger grossly underestimates the amount of work I need to do each day.

It's not a big deal, but it would be a nice QoL improvement to have a way to get TimeTagger to ignore Saturday and Sunday in target computation.

**Comment by bernardpaulus** [comment]
Hello @almarklein 

This seemed like a great issue to get started with tinkering with Timetagger. I tried adding a 5-day "Work Week" time interval to solve this, however with my current (dumb) solution, I have a zoom out issue.

Indeed, when, coming from the "Hour" zoom level, I first zoom out to my new "Work Week", and then try to zoom out again to the "Week" level, it zooms out to the week, to immediately zoom back in to the "Work Week" zoom level.

Any ideas?

**Comment by almarklein** [comment]
I don't think the solution to this issue is to add an additional zoom level. The OP's main concern is that when setting daily targets, in the week view they are partially met, because of the two non-work days in the weekend. And a similar issue when the other way around.

The correct solution, IMO is to take number-of-work-days-per-week into account when calculating representative estimates of targets. This means we need an option to set this number somewhere. Making it a global setting is relatively easy, but people may want different values depending on the kind of thing they're tracking. So ideally it would be a per-target or a per-tag setting, and its a bit trickier to add settings for that.

I think this should be part of #121.
