### ISSUE TITLE
Some slow loading times (especially PWA)

### ISSUE THREAD

**Issue by Tagirijus** [almarklein/timetagger#461]
Edit: I am using v23.9.2 - did not test on staging yet.

# Slow PWA

Is it normal that the PWA on my mobile starts in around 10 seconds? It is hosted on a server, which seem to respond really fast, when accessing the app in the browser. Maybe it depends on my old mobile? It's a Huawai 2017 P8 or something ... it's like 7 years old now, I guess. Going to look for another mobile anyway soon, yet still I wanted to ask, if you or some users might have faced really slow opening of the app as well. It is ok, if the app started already and you just switch to the app then.

Edit: I found out that the PWA starts faster if I already started the browser app I am using. So: Firefox on Android unfortunately starts rather slow on my phone ... I guess that's why the PWA obviously starts slow as well. So in the end I think this part of this issue is a mix of "old phone" and "Firefox slow starting" ...

# Slow entries loading

Another thing: the app accessed through the browser (Firefox in my case) is visible almost immediately, yet showing the tracking data needs around 2 seconds here. Is this normal? Or on what could this depend on? Maybe I made some mistake setting up the server or so (I am running the nonroot docker image via a Hetzner CloudServer with 2 CPUs and 4 GB RAM) ... or you say it's normal since the DB has to be initialized first or so? It happens with just one entry already, by the way.

Edit: regarding the 2-3 seconds loading of the tracking entries: I just checked the demo on my server: those data get displayed immediately! I named some tags like _"1/client"_. Can this become a problem in any way? Or what else could be the matter here? /-:

Thanks for you answer! (=

**Comment by Tagirijus** [comment]
Sorry for the link to issue 1 - my example above with _"1/client"_ had a hash sign in the first edit of my post ... this made github link to this old issue immediately - oopsie ...

**Comment by almarklein** [comment]
The slow loading is likely because it needs to load all resources (on a slow device). The second  (and third. etc.) time the resources are loaded from cache so its much faster. It's likely that PWA's have their own cache separate from the browser.

Loading the entries from the db can indeed take a second or two. This is because any "sync trigger" will invoke a timer to prevent updates in great succession. The sync invoked when the page is loaded goes via the same process, thus the delay. Nothing related to your server or device being slow. The demo does not show this delay because it generates fake records, it does not actually load anything from anywhere, so it does not have the mechanism with the time.
