### ISSUE TITLE
App is non-functional on iOS during (when dailight saving time transitions in spring)

### ISSUE THREAD

**Issue by birdsarah** [almarklein/timetagger#73]
I'm on Safari on iOS 14.4 on an ipad.

Timetagger is non-functinal. Most of the time it doesn't load at all. Sometimes some UI loads, but it can't be interacted with.

I had timeturtle working on iOS previously.

**Comment by almarklein** [comment]
Hi Sarah!

Eek! I guess I broke it [again](https://github.com/almarklein/timetagger/pull/22). Sorry for the inconvenience! I'll have a look first thing tomorrow. Is it possible to get the dev console on an IPad to see any errors? I'll probably try to reproduce it via a run-an-IPad-in-the-cloud service anyway though.

**Comment by almarklein** [comment]
Tried for a bit just now. I can reproduce that the app is not/barely responsive. But I don't see any errors in the dev console :/  Will look again tomorrow. Do you happen to know when was the last time that it worked correctly on that device? I could scan the latest changes and check some suspicions ...

**Comment by birdsarah** [comment]
Hi. Sorry, I am useless to you. I (a) don't have a mac to do dev console and (b) yesterday was the first day i tried to load timetagger on my ipad.

**Comment by almarklein** [comment]
I seem to have narrowed it down to ... the daylight savings time transition! What are the odds, you got lucky! Or maybe not, but I'm happy that we found this bug :)  Ok, now to find out why it occurs specifically on ios, and fix it.

**Comment by almarklein** [comment]
Fixed!

Quick summary:
* The bug is present when the transition to daylight saving time in spring is present in the timeline, at certain tick-resolutions.
* The bug seems limited to Safari on iOS.
* The bug was caused, because in the while loops that generate ticks, the tick does not advance, preventing the while-loop from finishing. There are actually two while loops (one for major and one for minor tick marks). The first was protected by a max iter, the latter was not.
* Fixed by improving the code that advances a tick, and also checking the advancement.

**Comment by almarklein** [comment]
@birdsarah Thanks a lot for reporting this!

**Comment by almarklein** [comment]
New version is released and deployed.
