### ISSUE TITLE
Delete records via API

### ISSUE THREAD

**Issue by GormanFletcher** [almarklein/timetagger#91]
Is there a way to delete records via the API?

**Comment by almarklein** [comment]
Yes. From the server point of view, there is no way to delete a record, because a deletion cannot be synced. So the way to "delete" a record is to make the description start with "HIDDEN" - the client will hide such records:

https://github.com/almarklein/timetagger/blob/13d355df51fb792cd5fb5871b40bb0fbc4131104/timetagger/app/stores.py#L167-L169

**Comment by almarklein** [comment]
This should probably be documented in the API docs though, leaving this issue open to track this.

**Comment by GormanFletcher** [comment]
Perfect, thanks!

Just to put it on your radar, the last time I worked on a project with 2-way data sync, I found [this great blog post](http://blog.ezyang.com/2012/08/how-offlineimap-works/) on how OfflineIMAP syncs deletions without tombstoning. Reading the comments, OfflineIMAP still has sync problems because IMAP is a mess, but the algorithm seemed solid to me.

**Comment by almarklein** [comment]
Thanks for the link! I'm not sure if an approach like that could work with the synchronization approach implemented now, and there's not so much a need to avoid tombstoning. An interesting read nonetheless :)

**Comment by jmetz** [comment]
> Yes. From the server point of view, there is no way to delete a record, because a deletion cannot be synced. So the way to "delete" a record is to make the description start with "HIDDEN" - the client will hide such records:
> 
> https://github.com/almarklein/timetagger/blob/13d355df51fb792cd5fb5871b40bb0fbc4131104/timetagger/app/stores.py#L167-L169

I know this is already closed, but seeing a bunch of "HIDDEN" entries in the `search records and tags` dialog seems pretty unpleasant - @almarklein could you explain / link to an explanation of why true record deletes isn't possible (can't be synced)? 

A workaround could be to have two "hidden" tags - HIDDEN and DELETED - the later should appear nowhere on the front-end at all IMO. Or stick to just HIDDEN but make these tasks be truly hidden (from the search also).

**Comment by almarklein** [comment]
> but seeing a bunch of "HIDDEN" entries in the search records and tags dialog seems pretty unpleasant

Ah, then this will need to be fixed. #271

> could you explain / link to an explanation of why true record deletes isn't possible (can't be synced)?

Well, imagine you have two devices on which you use TimeTagger. If you delete a record on one device, that change (the record being deleted) has to propagate to the server and then to the other device. Simply throwing away the record won't work, because you need *something* to propagate.

**Comment by almarklein** [comment]
This is starting to become rather technical now :)  Synchronization is really hard to do well. 

The way things work in TimeTagger is that it stores a collection of records, each have a number indicating when they've last been changed (wrt the server time) That way a client can get the latest version of all records that have been changed since a certain time.

What you're proposing could also work, but the server may have to store this diff messages as well, which can be complicated to manage.

As for payload, records take up very little memory.

**Comment by jmetz** [comment]
Yeah I see what you mean re having to also store a diff table (and then each client would get all diffs since a specific time). I think after discussing it a bit, while the "diffs approach" I suggested might be cleaner, just storing some sort of `deleted` flag with each record would probably be simpler overall (even if just done as a special start string in the title... though a separate flag would be best!). 

I think as long as all front-ends honor the convention properly there's nothing wrong with that, and  https://github.com/almarklein/timetagger/issues/271 addresses that issue. 

Anyway, thanks for indulging this little aside on these details :+1:

**Comment by almarklein** [comment]
>  though a separate flag would be best!

Yeah, that would be cleaner. Certainly something I considered. But most records are not deleted, and deleted records don't really need their description field anymore, so I took the more practical solution 😄
