### ISSUE TITLE
Introduce a zoom level to view multiple whole weeks

### ISSUE THREAD

**Issue by HexaCubist** [almarklein/timetagger#96]
When I zoom out to the point where I can view each week's hours as a single block (this is the month view), the user interface attempts to automatically scroll to snap things into view, but I've never found this to be consistent.

As it stands, it seems to be snapping to something other than week boundaries (perhaps months?). When I'm dragging this view back in time, it will sometimes move several weeks ahead or back in time to do this, making me lose sight of the week I want to be looking at. As far as I can tell, there's no other way to view things week-by-week except by selecting dates manually.

**Comment by almarklein** [comment]
Thanks for the feedback!

Yes, at that zoom level the timelime attempts to snap to whole months. As you then manually move the timeline it will indeed not snap to whole weeks.

As I understand it, you'd like to blocks for a couple of (whole) weeks, and moving back/foward in time should snap to week boundaries.

I can certainly see the value of that. The timeline's snapping behavior is based on the zoom level, so to implement what you want we may need to introduce a new zoom level between the month-level and 3-month/quarter level. Perhaps at 6 or 8 weeks?

Another idea might be to start snapping to weeks as you manually move the timeline at the month zoom level. I'm not sure yet how well this will work though, since there may be ambiguity when the first day of the month is on monday: should it snap to weeks or to the month.

**Comment by HexaCubist** [comment]
Cheers! Really awesome product you have :) I think it would make sense as you said to have something like an 8-week zoom level where you can still seed individual weeks if that's possible. You're totally right about it not working to snap at week-level on that zoom setting  as it would mess with the months snapping.

**Comment by almarklein** [comment]
I changed the title to reflect the required new feature. Notes for myself:
* Introduce extra zoom level for multi-week-overview.
* See if we can change the scrolling behavior in the month-zoom-level.

**Comment by almarklein** [comment]
I implemented this, and the latest version is now online.

**Comment by almarklein** [comment]
After using this for a while, I find the 4-day steps in the month view incredibly confusing. I just deployed a change that replaces the 7-week level with a 3-week level. Let me know if this does / does not work for you! :)

**Comment by HexaCubist** [comment]
No worries, it's not quite as perfect for my use case but I'll admit it does make more sense :) Awesome, cheers!

**Comment by almarklein** [comment]
Was still not happy. I changed it again in #100. The multi-week view is back at 7 weeks.

**Comment by HexaCubist** [comment]
Brilliant! Yes, all good - that makes sense to me. Thanks again for the awesome tool :)
